---
title: TeachOSM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
include:
- pages
