---
title: TeachOSM
timezone: UTC

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: ['pages']

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
