---
title: TeachOSM
timezone: UTC
collections:
  filters:
    title: Filters
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
collections_dir: collections
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate-v2
include:
- pages
pagination:
  collection: posts
  debug: true
  enabled: true
  per_page: 4
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
permalink: "/:year/:month/:title.html"
