---
title: TeachOSM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
collections_dir: collections
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
include:
- pages
