---
title: TeachOSM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  lessons:
    title: Lessons
    output: true
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
include:
- pages
